import { NextRequest, NextResponse } from "next/server";
import { database } from "@/lib/db";
import { sanitizeValue } from "@/lib/privacy";
import type { Session, Step } from "@/lib/model";
const tools=[
 {name:"get_pending_question",description:"Read the highest-priority unresolved question for a session.",inputSchema:{type:"object",properties:{sessionId:{type:"string"}},required:["sessionId"]}},
 {name:"get_decision_context",description:"Read a compact, sanitized decision with provenance.",inputSchema:{type:"object",properties:{sessionId:{type:"string"},invoiceId:{type:"string"}},required:["sessionId","invoiceId"]}},
 {name:"get_guardrails",description:"Read confirmed guardrails for a session.",inputSchema:{type:"object",properties:{sessionId:{type:"string"}},required:["sessionId"]}},
 {name:"get_relevant_rules",description:"Read confirmed rules and exceptions for a session.",inputSchema:{type:"object",properties:{sessionId:{type:"string"}},required:["sessionId"]}},
 {name:"get_teachback_summary",description:"Read the confirmed workflow summary.",inputSchema:{type:"object",properties:{sessionId:{type:"string"}},required:["sessionId"]}},
 {name:"save_expert_answer",description:"Save an expert answer to an existing question. Requires approval.",inputSchema:{type:"object",properties:{sessionId:{type:"string"},question:{type:"string"},answer:{type:"string"}},required:["sessionId","question","answer"]}},
 {name:"mark_question_resolved",description:"Mark an existing question as resolved. Requires approval.",inputSchema:{type:"object",properties:{sessionId:{type:"string"},question:{type:"string"}},required:["sessionId","question"]}}
];
function rpc(id:unknown,result:unknown){return NextResponse.json({jsonrpc:"2.0",id,result},{headers:{"MCP-Protocol-Version":"2025-06-18"}})}
function error(id:unknown,message:string,code=-32603){return NextResponse.json({jsonrpc:"2.0",id,error:{code,message}},{status:code===-32600?400:200})}
export async function POST(request:NextRequest){if(!process.env.MCP_SHARED_SECRET||request.headers.get("authorization")!==`Bearer ${process.env.MCP_SHARED_SECRET}`)return new NextResponse("Unauthorized",{status:401});const body=await request.json().catch(()=>null);if(!body||body.jsonrpc!=="2.0")return error(body?.id||null,"Invalid JSON-RPC",-32600);if(body.method==="initialize")return rpc(body.id,{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"ai-apprentice-memory",version:"0.1.0"}});if(body.method==="notifications/initialized")return new NextResponse(null,{status:202});if(body.method==="tools/list")return rpc(body.id,{tools});if(body.method!=="tools/call")return error(body.id,"Method not found",-32601);
 const name=body.params?.name;const args=body.params?.arguments||{};if(!tools.some(t=>t.name===name)||typeof args.sessionId!=="string")return error(body.id,"Unknown tool or missing sessionId",-32602);const db=database();if(!db)return error(body.id,"Database is not configured");let state:Session;try{const rows=await db`SELECT state FROM sessions WHERE id=${args.sessionId} LIMIT 1`;if(!rows[0])return error(body.id,"Session not found");state=rows[0].state as Session;}catch{return error(body.id,"Database unavailable")}
 let value:unknown;const confirmed=(state.steps||[]).filter((x:Step)=>x.status==="confirmed");switch(name){case "get_pending_question":value=(state.steps||[]).find((x:Step)=>x.status==="unresolved")?.question||null;break;case "get_decision_context":value=(state.steps||[]).filter((x:Step)=>x.invoiceId===args.invoiceId).map((x:Step)=>({decision:x.decision,reason:x.answer||x.reason,guardrail:x.guardrail,correction:x.correction,screenMoment:x.moment,sourceDecision:x.id,confirmed:x.status==="confirmed",confidence:x.status==="confirmed"?1:.5}));break;case "get_guardrails":value=confirmed.map((x:Step)=>({text:x.guardrail,correction:x.correction,sourceDecision:x.id,screenMoment:x.moment,confirmed:true,confidence:1}));break;case "get_relevant_rules":value=confirmed.map((x:Step)=>({decision:x.decision,reason:x.answer||x.reason,correction:x.correction,sourceDecision:x.id,screenMoment:x.moment,confirmed:true,confidence:1}));break;case "get_teachback_summary":value={confirmed:state.teachbackConfirmed,steps:confirmed.map((x:Step)=>({title:x.title,decision:x.decision,reason:x.answer||x.reason,guardrail:x.guardrail,correction:x.correction}))};break;case "save_expert_answer":{if(typeof args.question!=="string"||typeof args.answer!=="string")return error(body.id,"Invalid answer",-32602);const answer=sanitizeValue(args.answer) as string;state.answers.push({question:args.question,answer,ts:Date.now()});state.steps=state.steps.map((x:Step)=>x.question===args.question?{...x,answer,reason:answer,status:"confirmed"}:x);value={saved:true};break}case "mark_question_resolved":{if(typeof args.question!=="string")return error(body.id,"Invalid question",-32602);state.steps=state.steps.map((x:Step)=>x.question===args.question?{...x,status:"confirmed"}:x);value={resolved:true};break}}
 if(name==="save_expert_answer"||name==="mark_question_resolved"){try{await db`UPDATE sessions SET state=${JSON.stringify(sanitizeValue(state))}::jsonb WHERE id=${state.id}`;}catch{return error(body.id,"Save failed")}}
 return rpc(body.id,{content:[{type:"text",text:JSON.stringify(sanitizeValue(value))}]});
}
