export type WorkflowEvent = { eventId:string; sessionId:string; ts:number; source:"native_app"|"browser_observer"|"vision"|"speech"; kind:"navigation"|"field_change"|"decision"|"submit_attempt"|"document_opened"|"artifact_selected"|"status_change"; actor:"expert"|"trainee"; object?:{type:string;id?:string}; action?:string; before?:unknown; after?:unknown; context?:Record<string,unknown>; artifactRefs?:{kind:string;locator:string}[]; evidenceRequirements?: ("structured"|"screen"|"document")[]; confidence?:number };
export type Step = {id:string;invoiceId:string;title:string;moment:string;ts:number;decision:string;reason:string;reasonQuote:string;guardrail:string;status:"unresolved"|"confirmed";evidence:string;question:string;answer?:string;correction?:string};
export type Session = {id:string;startedAt:number;offRecord:boolean;events:WorkflowEvent[];steps:Step[];answers:{question:string;answer:string;ts:number}[];teachbackConfirmed:boolean;teachbackCorrection:string;traineeAttempts:{invoiceId:string;choice:string;blocked:boolean;ts:number}[]};
export const SESSION_KEY="apprentice-demo-v1";
export function newSession():Session {return {id:crypto.randomUUID(),startedAt:Date.now(),offRecord:false,events:[],steps:[],answers:[],teachbackConfirmed:false,teachbackCorrection:"",traineeAttempts:[]};}
export function readSession():Session {if(typeof window==="undefined") return newSession();try {const s=localStorage.getItem(SESSION_KEY);return s?JSON.parse(s):newSession();}catch{return newSession();}}
export function saveSession(s:Session){if(typeof window!=="undefined") localStorage.setItem(SESSION_KEY,JSON.stringify(s));}
export function eventFor(s:Session, actor:WorkflowEvent["actor"], kind:WorkflowEvent["kind"], invoiceId:string, action:string, before?:unknown, after?:unknown):WorkflowEvent{return {eventId:crypto.randomUUID(),sessionId:s.id,ts:Date.now(),source:"native_app",kind,actor,object:{type:"invoice",id:invoiceId},action,before,after,context:{route:typeof window!=="undefined"?location.pathname:""},evidenceRequirements:["structured","screen","document"],confidence:1};}
export const liveQuestions:Record<string,{reason:string;guardrail:string;question:string;title:string}>={
 "INV-4471":{title:"Recode the equipment invoice",question:"I saw you move INV-4471 to capex. What made that the right choice, and is there a limit?",reason:"Equipment over €5,000 is always capex.",guardrail:"No asset number, no capex booking. Unknown supplier: stop and ask the controller."},
 "INV-4472":{title:"Hold a December duplicate risk",question:"You held the December invoice. Is that for every supplier, and who decides when to release it?",reason:"This supplier has double-billed in December before; hold it until the duplicate check clears.",guardrail:"Do not release a suspected duplicate without controller review."},
 "INV-4473":{title:"Request second approval",question:"I noticed the Czech subsidiary invoice went for a second approval. When is that required, and who approves it?",reason:"Cross-border invoices from the Czech subsidiary need a second approver.",guardrail:"Never post the invoice before that approval is recorded."}
};
export const debriefQuestions=["Does the €5,000 capex rule include exactly €5,000, and who confirms a missing asset number?","What evidence clears a suspected December duplicate, and what if the controller cannot be reached?","What should a new hire do if the Czech subsidiary approver is unavailable, and are there any exceptions?"];
